#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
################################################################################
#  Load Packages
################################################################################
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



# Packages
library(purrr)
library(tidyverse)
library(randomForest)
library(ranger)
#remotes::install_github("valentinitnelav/plotbiomes")
#library(plotbiomes)
library(ggpubr)
library(oce)
library(gridBase)
library(grid)
library(maps)
library(mapdata)
#devtools::install_github("ropenscilabs/ochRe")
library(ochRe)
library(scales)
library(ggsci)
library(ggpubr)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(dplyr)
#library(maptools)
library(maps)
library(rworldmap)
library(countrycode)
library(raster)
library(caret)
library(RRF)
library(ggbreak) 
library(patchwork)
library(rBayesianOptimization)
library(xgboost)
library(ggalluvial)
library(ggthemes)
library(missMDA)
library(factoextra)
library(FactoMineR)
library(xgboost)
library(missForest)
library(raster)
#library(rgdal)
library(sp)
library(dplyr)
library(ggstatsplot)
library(vcfR)
library(leaflet)
#devtools::install_github("jiabowang/GAPIT", force=TRUE)
library(GAPIT)
library(vroom)
library(GenomicRanges)
library(graphics)


